# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4a311735963dfdc2e612b2980f8eb730d71642cfd9de90e80e6f466c94af73970b020ff801460017600a161913201d42cf07f839294c8aaa05d5634629415f2

test:
  secret_key_base: 3af5730c639f9a29c02867fc3813ac2ce72b1a4d0fea3c47793dff53a19423a10b3bab8dc11515936accdda0fd18ed39151bcae256a6743d3aa5e5e65a191b01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
